config/routes.rb
Rails.application.routes.draw do

  # API routes
  namespace :api, defaults: {format: :json} do
    # Speacial Admin API routes
    namespace :admin do
      get :owners, to: "owners#index"
    end
  end

  # Admin routes
  namespace :admin do
    root to: 'sem_apps#index'

    get   :application_settings, to: 'application_settings#index'
    patch :application_settings, to: 'application_settings#update'

    resources :mailings, only: [:new, :create]

    resources :sem_apps, path: 'apps', except: [:new, :create] do
      collection do
        match :filter, via: [:get, :post]
      end
      member do
        put :set_creator
      end
      resources :ownerships, shallow: true
    end

    resources :books,
          only: [:edit, :update, :destroy, :defer, :dedefer, :placed_in_shelf,
                  :removed_from_shelf, :reference, :set_ebook_reference] do
      member do
        put :defer
        put :dedefer
        put :placed_in_shelf
        put :removed_from_shelf
        put :reference
        put :set_ebook_reference
      end
    end

    resources :book_shelves, path: 'shelves', only: :index

    resources :scanjobs do
     member do
       put :defer
       put :dedefer
     end
     collection do
       put :upload
     end
    end

    get "attachment-checks", to: "attachment_checks#index", as: :attachment_checks

    match 'scanjobs/:id/print-job' => 'scanjobs#print_job', as: :scanjob_print_job, via: [:get, :post]
    match 'scanjobs/print-list/:list_name' => 'scanjobs#print_list', as: :scanjobs_print_list, via: [:get, :post]
    match 'scanjobs/:id/barcode' => 'scanjobs#barcode', as: :scanjob_barcode, via: [:get, :post]
  end

  resources :sessions, only: [:new, :create, :destroy]
  match 'login'         => 'sessions#new',     as: :login, via: [:get, :post]
  match 'logout'        => 'sessions#destroy', as: :logout, via: :get
  get   'switch/:login' => 'sessions#switch'
  get   'switch-back'   => 'sessions#switch_back'

  # User profile
  resource :user, only: [:show]

  # Sem Apps
  match "semester"        => 'sem_apps#semester_index', as: :semester_index, via: [:get, :post]
  match 'semester/filter' => 'sem_apps#filter_semester_index', as: :filter_semester_index, via: [:get, :post]

  resources :sem_apps, :path => 'apps' do
    member do
      post :unlock
      get  :clones
      post :clone
      post :filter_clones
      put  :generate_access_token
      get  :export, to: 'export#export', as: :export
      get  :import, to: 'import#new',    as: :new_import
      post :import, to: 'import#create', as: :import
    end

    collection do
      post :filter
    end

    resource :transit, only: [:new, :create], controller: :sem_app_transits

    resources :books

    resources :ownerships, :shallow => true

    resources :media, only: [:reorder, :new], shallow: true do
      collection do
        put :reorder
      end
      resources :file_attachments, path: 'attachments', only: [:edit, :update, :destroy]
      resources :scanjobs, path: 'scans', only: [:edit, :update, :destroy]
    end
    resources :media_headlines, path: 'headlines', shallow: true do
      # nope
    end
    resources :media_texts, path: 'texts', shallow: true do
      resources :file_attachments, path: 'attachments', only: [:new, :create]
    end
    resources :media_monographs, path: 'monographs', shallow: true do
      resources :file_attachments, path: 'attachments', only: [:new, :create]
      resources :scanjobs, path: 'scans', only: [:new, :create]
    end
    resources :media_articles, path: 'articles', shallow: true do
      resources :file_attachments, path: 'attachments', only: [:new, :create]
      resources :scanjobs, path: 'scans', only: [:new, :create]
    end
    resources :media_collected_articles, path: 'collected-articles', shallow: true do
      resources :file_attachments, path: 'attachments', only: [:new, :create]
      resources :scanjobs, path: 'scans', only: [:new, :create]
    end
  end

  # Download (secured download of attachments)
  match 'download/:id/:style/*other' => 'download#download', :as => :download, via: [:get, :post]

  # Static links
  get '/datenschutz', to: redirect("https://www.ub.uni-paderborn.de/fileadmin/ub/Dokumente_Formulare/DSE_UB_003_Seminarapparate.pdf")

  # Root Page
  root to: "home#index"

end

app/views/shared_partials/_ajax_flash_message.html.erb
<% if message %>
  <div id="_ajax_flash_<%=style || 'notice'-%>" style="display:none">
    <%= render 'shared_partials/flash_message', :style => (style || 'notice'), :message => message %>
  </div>
<% end %>

app/views/shared_partials/_ajax_flash_messages.html.erb
<%= render 'shared_partials/ajax_flash_message', :style => 'notice', :message => flash[:notice] %>
<%= render 'shared_partials/ajax_flash_message', :style => 'error',  :message => flash[:error] %>

<script type="text/javascript">
  jQuery(function() {
    notices = jQuery("#_ajax_flash_notice").html();
    errors  = jQuery("#_ajax_flash_error").html();

    if (notices || errors) {
      messages = "";
      if (notices != null) messages = messages + notices;
      if (errors != null) messages = messages + errors;
 
      jQuery("#flash_messages").empty().append(messages);
      jQuery("#_ajax_flash_notice").remove();
      jQuery("#_ajax_flash_error").remove();
    }
  });
</script>

app/views/shared_partials/_book_ref.erb
<%
  content = ""
  content                << content_tag(:span, book.title)
  content << " / "       << content_tag(:span, book.author)    if book.title.present? and book.author.present?
  content << ".- " << content_tag(:span, book.edition)   if book.edition.present?
  content << ".- "       << content_tag(:span, book.place)     if book.place.present?
  content << " : "       << content_tag(:span, book.publisher) if book.place.present? and book.publisher.present?
  content << ", "        << content_tag(:span, book.year)      if book.year.present?
  content << ".- ISBN "  << content_tag(:span, book.isbn)      if book.isbn.present?
  content = content.html_safe # TODO: Shouldn't we h-escape the content from the content tags?
%>

<div class="bib-ref">
  <%= content %>
</div>

app/views/shared_partials/_book_ref.html.erb
<%
  content = ""
  content                << content_tag(:span, book.title)
  content << " / "       << content_tag(:span, book.author)    if book.title.present? and book.author.present?
  content << ".- Aufl. " << content_tag(:span, book.edition)   if book.edition.present?
  content << ".- "       << content_tag(:span, book.place)     if book.place.present?
  content << " : "       << content_tag(:span, book.publisher) if book.place.present? and book.publisher.present?
  content << ", "        << content_tag(:span, book.year)      if book.year.present?
  content << ".- ISBN "  << content_tag(:span, book.isbn)      if book.isbn.present?
%>

<div class="bib-ref">
  <%= content %>
</div>

app/views/shared_partials/_flash_message.html.erb
<% if message and not message.empty? %>
  <% pui_panel :id => "flash_#{(style || 'notice')}", :class => "flash_message", :panel_style => (style || 'notice') do %>
    <%= message %>
  <% end %>
<% end %>

app/views/shared_partials/_flash_messages.html.erb
<% if flash[:success].present? %>
  <div class="pui-panel success align-center">
    <%= raw flash[:success] %>
  </div>
<% end %>
<% if flash[:notice].present? %>
  <div class="pui-panel notice align-center">
    <%= raw flash[:notice] %>
  </div>
<% end %>
<% if flash[:error].present? %>
  <div class="pui-panel error align-center">
    <%= raw flash[:error] %>
  </div>
<% end %>
<% if flash[:failure].present? %>
  <div class="pui-panel error align-center">
    <%= raw flash[:failure] %>
  </div>
<% end %>
<% if flash[:alert].present? %>
  <div class="pui-panel error align-center">
    <%= raw flash[:alert] %>
  </div>
<% end %>

app/views/shared_partials/_footer.html.erb
&copy; <%= Time.now.year %> <a href="http://www.ub.uni-paderborn.de">Universitätsbibliothek Paderborn</a> |
<a href="http://www.ub.uni-paderborn.de/ueber-uns/impressum/">Impressum</a> |
<a href="/datenschutz">Datenschutzerklärung</a>

app/views/shared_partials/_legal_info.html.erb
<div class="pui-overlay" id="legal-info">
  <h3 class="section">Rechtliche Hinweise zur Bereitstellung von Dokumenten in Seminarapparaten</h3>
  <p>
    Die Universitätsbibliothek möchte hier auf wichtige rechtliche Rahmenbedingungen hinweisen, die Sie als Dozent/Dozentin berücksichtigen müssen, wenn Sie einen Seminarapparat anbieten.
  </p>
  <p>
    <a href="https://www.ub.uni-paderborn.de/recherche/hinweise-zur-nutzung-der-elektronischen-angebote/60a-urhwissg/" target="_blank">Klicken Sie hier für weitere Informationen</a>.
  </p>
</div>

app/views/shared_partials/_main_navigation.html.erb
<div class="section">
  <h3>&raquo; Seminarapparate</h3>
  <ul>
    <li><%= link_to(Semester.current.title, semester_index_path) %></li>
    <li><%= link_to('Alle Apparate', sem_apps_path) %></li>
  </ul>
</div>

<div class="section">
  <h3>&raquo; Für Lehrende</h3>
  <ul>
    <% if current_user %>
      <li><%= link_to('Meine Seminarapparate', user_path) %></li>
    <% end %>
    <li><%= link_to('Seminarapparat beantragen', new_sem_app_path) %></li>
    <li><%= link_to('Rechtliche Hinweise', '#', :class => 'pui-overlay-trigger', :rel => '#legal-info') %></li>
  </ul>
</div>

<div class="section">
  <h3>&raquo; Video-Tutorials</h3>
  <div style="font-size:90%" class="pui-panel notice">
    <%= icon 'question-shield.png' %>
    Video-Tutorials für Lehrende zum Schnelleinstieg in die eSeminarapparate.
  </div>
  <ul>
    <li><%= link_to('Seminarapparat beantragen', 'https://www.youtube.com/watch?v=CB3uxXb_PsM', :target => 'blank') %></li>
    <li><%= link_to('Seminarapparat bearbeiten', 'https://www.youtube.com/watch?v=sp4XDDocTeE', :target => 'blank') %></li>
    <li><%= link_to('Dateien hochladen und Scan-Aufträge erstellen', 'https://www.youtube.com/watch?v=sp4XDDocTeE&t=194', :target => 'blank') %></li>
  </ul>
</div>

app/views/shared_partials/_main_navigation.html.erb.erb
<div class="section">
  <h3>&raquo; eSeminarapparate</h3>
  <ul>
    <li><%= link_to('Gesamtliste', sem_apps_path) %></li>
    <% if User.current %>
      <li><%= link_to('Meine eSeminarapparate', user_path(:anchor => 'apps')) %></li>
    <% end %>
  </ul>
</div>

<div class="section">
  <h3>&raquo; Für Lehrende</h3>
  <ul>
    <li><%= link_to('eSeminarappart beantragen', new_sem_app_path) %></li>
  </ul>
</div>

<% if User.current and User.current.is_admin? %>
<!--
  <div class="section">
    <h3>&raquo; für Admins</h3>
    <ul>
      <li><%= link_to 'Dashboard', admin_dashboard_path %></li>
      <li><%= link_to 'Benutzer verwalten', admin_users_path %></li>
      <li><%= link_to 'Standorte verwalten', admin_locations_path %></li>
      <li><%= link_to 'Semester verwalten', admin_semesters_path %></li>
    </ul>
  </div>
-->
<% end %>

app/views/shared_partials/_meta_navigation.html.erb
<% if current_user %>
  <span>
    Willkommen
    <strong><%= current_user.name %></strong>
  </span>

  <% if current_user.is_admin? %>
    <%= link_to admin_root_path do %>
      <%= icon 'user-black.png' %>
      Administration
    <% end %>
  <% end %>

  <%= link_to user_path do %>
    <%= icon 'user-orange.png' %>
    Meine Seminarapparate
  <% end %>

  <%= link_to logout_path, :data => {:confirm => 'Wirklich abmelden?'} do %>
    <%= icon 'door-open-out.png' %>
    Abmelden
  <% end %>
<% else %>
  <%= link_to login_path do %>
    <%= icon 'door-open-in.png' %>
    Login für Lehrende
  <% end %>
<% end %>

<a href="#" rel="#common-help" class="pui-overlay-trigger">
  <%= icon 'question-shield.png' %>
  Hilfe
</a>

app/views/shared_partials/_sem_app_states.html.erb
<% unless sem_app.approved? %>
  <%= icon 'exclamation-diamond.png' %>
  Wird von der Universitätsbibliothek überprüft
<% else %>
  <%= icon 'tick-circle.png' %>
  <span>Freigeschaltet</span>
<% end %>

app/views/shared_partials/_test_server_warning.html.slim
- if ENV["TEST_SERVER_WARNING"] == "true"
  #test-server-warning
    = "!!! TESTSERVER !!!"

app/views/shared_partials/unhandled_error.html.erb
<h3 class="section">Systemfehler</h3>

<div class="pui-panel error align-center">
  Es tut uns leid. Es ist ein Fehler aufgetreten. Die letzte Operation wurde abgebrochen.
  Bitte versuchen Sie es erneut. Sollte der Fehler weiterhin auftreten, wenden Sie sich bitte an
  den <a href="#" class="pui-overlay-trigger" rel="#common-help">technischen Support</a>.
</div>

<div class="pui-panel">
  <%= icon 'asterisk.png' %>
  <strong>Meldung:</strong>
  <code><%= exception.message %></code>
</div>

<div class="pui-view align-center">
  <%= link_to 'Zur Startseite', sem_apps_path, :class => 'pui-button' %>
</div>