config/routes.rb
Rails.application.routes.draw do

  # API routes
  namespace :api, defaults: {format: :json} do
    # Speacial Admin API routes
    namespace :admin do
      get :owners, to: "owners#index"
    end
  end

  # Admin routes
  namespace :admin do
    root to: 'sem_apps#index'

    get   :application_settings, to: 'application_settings#index'
    patch :application_settings, to: 'application_settings#update'

    resources :mailings, only: [:new, :create]

    resources :sem_apps, path: 'apps', except: [:new, :create] do
      collection do
        match :filter, via: [:get, :post]
      end
      member do
        put :set_creator
      end
      resources :ownerships, shallow: true
    end

    resources :books,
          only: [:edit, :update, :destroy, :defer, :dedefer, :placed_in_shelf,
                  :removed_from_shelf, :reference, :set_ebook_reference] do
      member do
        put :defer
        put :dedefer
        put :placed_in_shelf
        put :removed_from_shelf
        put :reference
        put :set_ebook_reference
      end
    end

    resources :book_shelves, path: 'shelves', only: :index

    resources :scanjobs do
     member do
       put :defer
       put :dedefer
     end
     collection do
       put :upload
     end
    end

    get "attachment-checks", to: "attachment_checks#index", as: :attachment_checks

    match 'scanjobs/:id/print-job' => 'scanjobs#print_job', as: :scanjob_print_job, via: [:get, :post]
    match 'scanjobs/print-list/:list_name' => 'scanjobs#print_list', as: :scanjobs_print_list, via: [:get, :post]
    match 'scanjobs/:id/barcode' => 'scanjobs#barcode', as: :scanjob_barcode, via: [:get, :post]
  end

  resources :sessions, only: [:new, :create, :destroy]
  match 'login'         => 'sessions#new',     as: :login, via: [:get, :post]
  match 'logout'        => 'sessions#destroy', as: :logout, via: :get
  get   'switch/:login' => 'sessions#switch'
  get   'switch-back'   => 'sessions#switch_back'

  # User profile
  resource :user, only: [:show]

  # Sem Apps
  match "semester"        => 'sem_apps#semester_index', as: :semester_index, via: [:get, :post]
  match 'semester/filter' => 'sem_apps#filter_semester_index', as: :filter_semester_index, via: [:get, :post]

  resources :sem_apps, :path => 'apps' do
    member do
      post :unlock
      get  :clones
      post :clone
      post :filter_clones
      put  :generate_access_token
      get  :export, to: 'export#export', as: :export
      get  :import, to: 'import#new',    as: :new_import
      post :import, to: 'import#create', as: :import
    end

    collection do
      post :filter
    end

    resource :transit, only: [:new, :create], controller: :sem_app_transits

    resources :books

    resources :ownerships, :shallow => true

    resources :media, only: [:reorder, :new], shallow: true do
      collection do
        put :reorder
      end
      resources :file_attachments, path: 'attachments', only: [:edit, :update, :destroy]
      resources :scanjobs, path: 'scans', only: [:edit, :update, :destroy]
    end
    resources :media_headlines, path: 'headlines', shallow: true do
      # nope
    end
    resources :media_texts, path: 'texts', shallow: true do
      resources :file_attachments, path: 'attachments', only: [:new, :create]
    end
    resources :media_monographs, path: 'monographs', shallow: true do
      resources :file_attachments, path: 'attachments', only: [:new, :create]
      resources :scanjobs, path: 'scans', only: [:new, :create]
    end
    resources :media_articles, path: 'articles', shallow: true do
      resources :file_attachments, path: 'attachments', only: [:new, :create]
      resources :scanjobs, path: 'scans', only: [:new, :create]
    end
    resources :media_collected_articles, path: 'collected-articles', shallow: true do
      resources :file_attachments, path: 'attachments', only: [:new, :create]
      resources :scanjobs, path: 'scans', only: [:new, :create]
    end
  end

  # Download (secured download of attachments)
  match 'download/:id/:style/*other' => 'download#download', :as => :download, via: [:get, :post]

  # Static links
  get '/datenschutz', to: redirect("https://www.ub.uni-paderborn.de/fileadmin/ub/Dokumente_Formulare/DSE_UB_003_Seminarapparate.pdf")

  # Root Page
  root to: "home#index"

end

app/controllers/admin/sem_apps_controller.rb
class Admin::SemAppsController < Admin::ApplicationController

  SEM_APP_FILTER_NAME = 'admin_sem_app_filter_name_p'.freeze

  def index
    @filter   = SemAppsFilter.get_filter_from_session(session, SEM_APP_FILTER_NAME)
    @filtered = @filter.filtered?(except: [:unapproved, :book_jobs])

    @sem_apps = @filter.filtered
      .page(params[:page])
      .per_page(10)
      .reorder("sem_apps.created_at desc")
  end

  def filter
    SemAppsFilter.set_filter_in_session(session, params[:filter], SEM_APP_FILTER_NAME)
    redirect_to :action => :index
  end

  def show
    @sem_app = SemApp.find_by_id(params[:id])

    unless @sem_app.present?
      flash[:error] = "Dieser Apparat existiert nicht"
      redirect_to admin_sem_apps_path and return
    end

    @ordered_books  = Book.for_sem_app(@sem_app).ordered.ordered_by('signature asc')
    @removed_books  = Book.for_sem_app(@sem_app).removed.ordered_by('signature asc')
    @deferred_books = Book.for_sem_app(@sem_app).deferred.ordered_by('signature asc')

    respond_to do |format|
      format.html { render 'show',  :format => 'html' }
      format.print { render 'show', :format => 'print', :layout => 'print' }
    end
  end

  def edit
    @sem_app = SemApp.find(params[:id])
    @sem_app.build_book_shelf unless @sem_app.book_shelf.present?
    @sem_app.build_book_shelf_ref unless @sem_app.book_shelf_ref.present?
  end

  def update
    @sem_app = SemApp.find(params[:id])

    was_approved = @sem_app.approved

    if @sem_app.update(permitted_params)
      if (@sem_app.approved and not was_approved and @sem_app.creator.present? and @sem_app.creator.email.present?)
        Notifications.sem_app_activated_notification(@sem_app).deliver
      end
      flash[:success] = "Die Daten wurden erfolgreich gespeichert"
      redirect_to :action => :show
    else
      render :action => :edit
    end
  end

  def set_creator
    @sem_app = SemApp.find(params[:id])

    login     = params[:login].upcase
    alma_user = AlmaConnector.resolve_user(login)

    if alma_user
      user = User.find_by(ilsuserid: alma_user.primary_id)

      if user
        if @sem_app.update_attribute(:creator, user)
          flash[:success] = ActionController::Base.helpers.sanitize "Besitzer erfolgreich gesetzt. #{login} kann den Seminarapparat <i>#{@sem_app.title}</i> nun bearbeiten."
        else
          flash[:error] = "Fehler: Der Benutzer konnte nicht als Besitzer eingetragen werden."
        end
      else
        u = User.new(ilsuserid: alma_user.primary_id, login: login)

        if u.save(validate: false) and @sem_app.update_attribute(:creator, u)
          flash[:success] = ActionController::Base.helpers.sanitize "Der Benutzer '#{login}' existierte nicht, wurde aber angelegt. Name und E-Mail sind erst verfügbar wenn der Nutzer sich das erste mal anmeldet. #{login} kann den Seminarapparat <i>#{@sem_app.title}</i> nun bearbeiten."
        else
          flash[:error] = "Es ist ein unbekannter Fehler aufgetreten!"
        end
      end
    else
      flash[:error] = "Ein Nutzer mit der Bibliotheksausweisnummer #{login} existiert nicht."
    end

    redirect_to admin_sem_app_path(@sem_app, :anchor => 'users')
  end

  def destroy
    @sem_app = SemApp.find(params[:id])
    @sem_app.destroy
    flash[:success] = "Seminarpparat '#{@sem_app.title}' gelöscht."
    redirect_to :action => :index
  end

private

  def permitted_params
    params.require(:sem_app).permit(
      :approved,
      :semester_id,
      :title,
      :course_id,
      :tutors,
      :location_id,
      :shared_secret,
      book_shelf_attributes: [:slot_number, :ils_account, :_destroy, :id],
      book_shelf_ref_attributes: [:sem_app_ref_id],
    )
  end

end

app/controllers/sem_apps_controller.rb
class SemAppsController < ApplicationController

  SEM_APP_FILTER_NAME                 = 'sem_app_filter_name_p'.freeze
  SEM_APP_SEMESTER_INDEX_FILTER_NAME  = 'sem_app_semester_index_filter_name_p'.freeze
  SEM_APP_CLONES_FILTER_NAME          = 'sem_app_clones_filter_name_p'.freeze

  before_action :authenticate!, only: [:new, :create, :edit, :update, :generate_access_token, :clones, :filter_clones, :clone]

  def index
    @filter          = SemAppsFilter.get_filter_from_session(session, SEM_APP_FILTER_NAME)
    @filter.approved = true
    @filtered        = @filter.filtered?(except: :approved)

    @sem_apps = @filter.filtered
      .page(params[:page])
      .per_page(10)
  end

  def filter
    SemAppsFilter.set_filter_in_session(session, params[:filter], SEM_APP_FILTER_NAME)
    redirect_to :action => :index
  end

  def semester_index
    @filter             = SemAppsFilter.get_filter_from_session(session, SEM_APP_SEMESTER_INDEX_FILTER_NAME)
    @filter.approved    = true
    @filter.semester_id = Semester.current.id
    @filtered           = @filter.filtered?(except: [:approved, :semester_id])

    @sem_apps = @filter.filtered
      .page(params[:page])
      .per_page(10)
  end

  def filter_semester_index
    SemAppsFilter.set_filter_in_session(session, params[:filter], SEM_APP_SEMESTER_INDEX_FILTER_NAME)
    redirect_to :action => :semester_index
  end

  def show
    load_sem_app or return
    authorize! :read, @sem_app

    # check for access token
    token = params[:token]
    if token.present?
      if @sem_app.access_token == token
        @sem_app.unlock_in_session(session)
      else
        @sem_app.lock_in_session(session)
      end
      redirect_to :action => :show
    end

    @books = Book.for_sem_app(@sem_app).in_shelf.ordered_by("title")
    @media = @sem_app.media
  end

  def new
    @sem_app = SemApp.new
    @sem_app.tutors = current_user.name
  end

  def create
    @sem_app = SemApp.new(params.require(:sem_app).permit(
      :semester_id, :title, :course_id, :tutors, :location_id, :shared_secret, :accepts_copyright, :fachzuordnung
    ))
    authorize! :create, @sem_app

    @sem_app.creator = current_user

    # Map Fach to location
    location_id = SemApp2.config.fachzuordnungen&.find{|f| f.id == params[:sem_app][:fachzuordnung].to_i}&.location_id
    @sem_app.location = Location.find_by(id: location_id)

    # Finally create the semapp and add the ownership
    if @sem_app.save
      flash[:success] = """
          <p>Ihr Seminarapparat wurde erfolgreich beantragt. Wir prüfen die Angaben und schalten
          den Seminarapparat nach erfolgter Prüfung für Sie frei. Sie sehen den Status unter
          <strong>Meine Seminarapparate</strong>. Bis zur Freischaltung können nur Sie den Seminarapparat
          sehen und bearbeiten.</p>
      """.html_safe

      Notifications.sem_app_created_notification(@sem_app).deliver

      redirect_to user_path(:anchor => 'apps')
    else
      if @sem_app.location.nil?
        @sem_app.errors.add(:fachzuordnung, "für das Fach konnte kein Standort ermittelt werden. Bitte wenden Sie sich an das Informationszentrum der Bibliothek.")
      end

      render :action => :new
    end
  end

  def edit
    load_sem_app or return
    authorize! :edit, @sem_app

    # Generate access token if no access token exists
    @sem_app.generate_access_token! if @sem_app.access_token.blank?
  end

  def update
    load_sem_app or return
    authorize! :edit, @sem_app

    if @sem_app.update(params.require(:sem_app).permit(:tutors, :shared_secret))
      flash[:success] = "Änderungen erfolgreich gespeichert."
      redirect_to sem_app_path(@sem_app)
    else
      render :action => :edit
    end
  end

  def unlock
    load_sem_app or return

    shared_secret = params[:shared_secret]

    if (shared_secret == @sem_app.shared_secret) or @sem_app.miless_passwords.map{|p| p.password}.include?(shared_secret)
      @sem_app.unlock_in_session(session)
    else
      flash[:error] = "Die eingegebene Kennung stimmt leider nicht. Texte und Medien können nicht freigeschaltet werden."
    end

    redirect_to sem_app_path(@sem_app, :anchor => 'media')
  end

  def generate_access_token
    load_sem_app or return
    authorize! :edit, @sem_app

    if @sem_app.generate_access_token!
      flash[:success] = 'Es wurde ein neuer Access Token erstellt. Alte Token sind jetzt nicht mehr gültig.'
    else
      flash[:error] = 'Ein neuer Token konnte nicht erstellt werden. Es ist ein Fehler aufgetreten.'
    end

    redirect_to edit_sem_app_path(@sem_app, :anchor => 'token')
  end

  def clones
    load_sem_app or return
    authorize! :edit, @sem_app

    @filter            = SemAppsFilter.get_filter_from_session(session, SEM_APP_CLONES_FILTER_NAME)
    @filter.approved   = true

    @sem_apps = @filter.filtered
     .page(params[:page])
     .per_page(10)

    unless current_user.is_admin?
      @sem_apps = @sem_apps.created_by(current_user)
    end
  end

  def filter_clones
    load_sem_app or return
    authorize! :edit, @sem_app

    SemAppsFilter.set_filter_in_session(session, params[:filter], SEM_APP_CLONES_FILTER_NAME)
    redirect_to :action => :clones
  end

  def clone
    load_sem_app or return
    authorize! :edit, @sem_app

    # Try to find the source sem app we want to clone
    source_sem_app = SemApp.find(params[:source])
    authorize! :edit, source_sem_app

    begin
      cloner = SemAppCloner.new(source_sem_app, @sem_app, clone_books: false, clone_media: true)
      cloner.clone!
      flash[:success] = 'Einträge wurden erfolgreich kopiert.'
    rescue Exception => e
      puts e.backtrace
      flash[:error] = 'Beim kopieren ist leider ein Fehler aufgetrten. Der Vorgang konnte nicht erfolgreich abgeschlossen werden.'
    end

    redirect_to sem_app_path(@sem_app, :anchor => 'media')
  end

private

  def load_sem_app
    begin
      id = params[:id]
      raise "No ID given" unless id

      m  = id.match /^m-(\d+)/
      if m and m[1]
        @sem_app = SemApp.find_by_miless_derivate_id!(m[1])
        flash[:notice] = """
          Sie haben einen alten Seminarapparat aufgerufen und wurden auf das neue System für
          elektronische Seminarapparate weitergeleitet. Bitte aktualisieren die Ihre Links und
          Lesezeichen auf diese neue URL.
        """
        redirect_to sem_app_path(@sem_app, :anchor => 'media') and return
      else
        @sem_app = SemApp.find_by_id!(id)
      end
    rescue
      flash[:error] = "Der Seminarapparat den Sie versucht haben aufzurufen existiert nicht."
      redirect_to sem_apps_path and return
    end

    return true
  end

end

app/views/admin/sem_apps/_book.erb
<div class="pui-view item section">
  Signatur: <strong><%= book.signature.presence || "–" %></strong>
  /
  Aleph/Alma ID: <%= link_to "http://katalog.ub.uni-paderborn.de/local/r/#{book.ils_id_formated}" do %>
    <strong><%= book.ils_id_formated %></strong><% end %>
  /
  Auftrag vom: <strong><%= book.updated_at.to_formatted_s(:short) %></strong>

  <% if book.placeholder? %>
    <%= icon 'asterisk.png' %>
    <strong>Stellvertreter</strong>
  <% end %>

  <%= render 'shared_partials/book_ref', :book => book %>

  <div class="pui-view align-right no-print">
    <% if book.state == Book::States[:deferred] %>
      <%= link_to 'Als Neu markieren', dedefer_admin_book_path(book), :method => :put, :class => 'pui-button small' %>
    <% end %>
    <% if book.state == Book::States[:ordered] or book.state == Book::States[:deferred] %>
      <%= link_to 'Auftrag löschen', admin_book_path(book), :method => :delete, :class => 'pui-button small', :data => {:confirm => 'Auftrag wirklich löschen?'} %>
      <%= link_to 'Wurde verbucht', placed_in_shelf_admin_book_path(book), :method => :put, :class => 'pui-button small' %>
    <% end %>
    <% if book.state == Book::States[:ordered] %>
      <%= link_to 'Wurde vorgemerkt', defer_admin_book_path(book), :method => :put, :class => 'pui-button small' %>
      <%= link_to 'Als Stellvertreter', edit_admin_book_path(book), :class => 'pui-button small' %>
      <%= link_to 'Als Präsenzexemplar', '#', :class => 'pui-button small pui-overlay-trigger', :rel => "#reference-copy-panel-#{book.id}" %>
      <%= link_to 'Als E-Book', '#', :class => 'pui-button small pui-overlay-trigger', :rel => "#ebook-reference-panel-#{book.id}" %>
    <% end %>
    <% if book.state == Book::States[:rejected] %>
      <%= link_to 'Wurde aus dem Regal entfernt', removed_from_shelf_admin_book_path(book), :method => :put, :class => 'pui-button small' %>
    <% end %>
  </div>

  <div class="only-print" style="margin-bottom: 30px">&nbsp;<!-- Notizen --></div>
</div>

<div id="reference-copy-panel-<%= book.id -%>" class="pui-overlay">
  <h3 class="section">Art des Präsenzexemplares</h3>
  <div class="align-center">
    <%= link_to 'Im Bestand', reference_admin_book_path(book, :ref_type => 1), :method => :put, :class => 'pui-button' %>
    <%= link_to 'In der Leihstelle', reference_admin_book_path(book, :ref_type => 2), :method => :put, :class => 'pui-button' %>
    <%= link_to 'Im ZfS', reference_admin_book_path(book, :ref_type => 3), :method => :put, :class => 'pui-button' %>
    <%= link_to 'IMT-Medien', reference_admin_book_path(book, :ref_type => 4), :method => :put, :class => 'pui-button' %>
  </div>
</div>

<div id="ebook-reference-panel-<%= book.id -%>" class="pui-overlay">
  <h3 class="section">Referenz zu einem E-Book setzen</h3>
  <%= semantic_form_for book, url: set_ebook_reference_admin_book_path(book), method: :put do |f| %>
    <%= f.inputs do %>
      <%= f.input :ebook_reference, :label => 'URL zum E-Book / Online-Resource', :required => true %>
    <% end %>

    <%= f.actions do %>
      <%= f.action :submit, label: 'Speichern' %>
    <% end %>
  <% end %>
</div>

app/views/admin/sem_apps/_books_to_remove.erb
<div class="pui-view">
  <% if @sem_app.books_to_remove.present? %>
    <div class="pui-panel align-center">
      <%= image_tag 'icons/minus.png', :plugin => 'pui' %>
      Die folgenden Bücher bitte aus dem Apparat entfernen
    </div>

    <% @sem_app.books_to_remove.each do |b| %>
      <%= render 'book', :book => b %>
    <% end %>
  <% else %>
    <div class="pui-panel success align-center">
      Aktuell keine Bücher zu entfernen
    </div>
  <% end %>
</div>

app/views/admin/sem_apps/_listing.html.erb
<% if @sem_apps.present?  %>
  <table class="pui-tableview">
    <thead>
      <tr>
        <th><%= "#{@sem_apps.count} Seminarapparat" %></th>
      </tr>
    </thead>
    <tbody>
      <% @sem_apps.each_with_index do |sem_app, n| %>
        <tr class="<%= (n % 2 == 0) ? 'even' : 'odd' -%>">
          <td>
            <% unless sem_app.approved? %>
              <%= icon 'star.png' %>
            <% end %>

            <% if Book.for_sem_app(sem_app).ordered.count > 0 %>
              <%= icon 'overlay/book--plus.png' %>
            <% end %>

            <% if Book.for_sem_app(sem_app).removed.count > 0 %>
              <%= icon 'overlay/book--minus.png' %>
            <% end %>

            <strong><%= link_to sem_app.title, admin_sem_app_path(sem_app) %></strong><br/>
            im <%= sem_app.semester.title %><br/>
            Dozent(en): <%= sem_app.tutors %><br/>
            Standort: <%= sem_app.location.title %>
            <% if sem_app.book_shelf.present? %>
              (Seminarapparat Nr. <%= sem_app.book_shelf.slot_number %>)
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="pui-view align-center">
    <%= will_paginate @sem_apps %>
  </div>
<% else %>
  <div class="pui-panel notice align-center">
    Keine Seminarapparate gefunden.
  </div>
<% end %>

app/views/admin/sem_apps/_remove_books_tab.erb
<div class="pui-view">
  <% if @remove_books.present? %>
    <div class="pui-panel align-center">
      <%= image_tag 'icons/minus.png', :plugin => 'pui' %>
      Die folgenden Bücher bitte aus dem Apparat entfernen
    </div>

    <% @remove_books.each do |b| %>
      <%= render 'book', :book => b %>
    <% end %>
  <% else %>
    <div class="pui-panel success align-center">
      Aktuell keine Bücher zu entfernen
    </div>
  <% end %>
</div>

app/views/admin/sem_apps/_users.erb
<h4 class="section">Besitzer</h4>
<div class="pui-view clearfix">
  <div class="grid_8 alpha">
    <div class="pui-collection-view labeled">
      <%= labeled_item :label => 'Benutzer',    :content => @sem_app.creator.name %>
      <%= labeled_item :label => 'E-Mail',      :content => mail_to(@sem_app.creator.email) %>
      <%= labeled_item :label => 'Ausweis Nr.', :content => @sem_app.creator.login %>
    </div>
  </div>
  <div class="grid_4 omega align-right">
    <%= link_to 'Besitzer neu festlegen', '#', :class => 'pui-button small pui-overlay-trigger', :rel => '#set-creator-panel' %>
  </div>
</div>

<h4 class="section">Weitere Nutzer mit Bearbeitungsrechten</h4>
<div class="pui-panel align-right">
  <%= link_to 'Nutzer hinzufügen', '#', :class => 'pui-button small pui-overlay-trigger', :rel => '#add-ownership-panel' %>
</div>
<% if @sem_app.ownerships.present? %>
  <% @sem_app.ownerships.each do |os| %>
    <div class="pui-view clearfix">
      <div class="grid_8 alpha">
        <div class="pui-collection-view labeled">
          <%= labeled_item :label => 'Benutzer',    :content => os.user.name %>
          <%= labeled_item :label => 'E-Mail',      :content => mail_to(os.user.email) %>
          <%= labeled_item :label => 'Ausweis Nr.', :content => os.user.login %>
        </div>
      </div>
      <div class="grid_4 omega align-right">
        <%= link_to admin_ownership_path(os), :class => 'pui-button small', :method => :delete, :data => {:confirm => 'Bearbeitungsrechte wirklich löschen?'} do %>
          Löschen
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="pui-panel align-center">
    <%= icon 'asterisk.png' %>
    Keine weiteren Nutzer haben Bearbeitungsrechte
  </div>
<% end %>



<div id="set-creator-panel" class="pui-overlay">
  <h3 class="section">Besitzer festlegen</h3>

  <div class="pui-panel">
    <%= icon 'asterisk.png' %>
    Wenn der Nutzer dem System nicht bekannt ist wird er automatisch angelegt. Name und E-Mail
    sind dann solange leer bis der Nutzer sich das erste mal anmeldet.
  </div>

  <%= form_tag(set_creator_admin_sem_app_path(@sem_app), :class => 'formtastic', :method => :put) do %>
    <fieldset class="inputs">
      <ol>
        <li class="string">
          <label for="login">Ausweis Nr.</label>
          <input type="text" style="width: 190px;" name="login"/>
        </li>
      </ol>
    </fieldset>
    <fieldset class="buttons">
      <ol>
        <li class="commit">
          <%= submit_tag 'Speichern' %>
        </li>
      </ol>
    </fieldset>
  <% end %>
</div>


<div id="add-ownership-panel" class="pui-overlay">
  <h3 class="section">Besitzer festlegen</h3>

  <div class="pui-panel">
    <%= icon 'asterisk.png' %>
    Wenn der Nutzer dem System nicht bekannt ist wird er automatisch angelegt. Name und E-Mail
    sind dann solange leer bis der Nutzer sich das erste mal anmeldet.
  </div>

  <%= form_tag(admin_sem_app_ownerships_path(@sem_app), :class => 'formtastic', :method => :post) do %>
    <fieldset class="inputs">
      <ol>
        <li class="string">
          <label for="login">Ausweis Nr.</label>
          <input type="text" style="width: 190px;" name="login"/>
        </li>
      </ol>
    </fieldset>
    <fieldset class="buttons">
      <ol>
        <li class="commit">
          <%= submit_tag 'Speichern' %>
        </li>
      </ol>
    </fieldset>
  <% end %>
</div>

app/views/admin/sem_apps/_users_tab.erb
<h5 class="section">Besitzer</h5>
<div class="pui-collection-view labeled">
  <%= labeled_item :label => 'Besitzer', :content => h(@sem_app.creator.name) %>
  <%= labeled_item :label => 'E-Mail',   :content => h(@sem_app.creator.email) %>
  <%= labeled_item :label => 'UB ID',    :content => h(@sem_app.creator.login) %>
</div>

<h5 class="section">Weitere Bearbeiter</h5>
<div class="pui-panel align-center">
  Die folgenden Benutzer können den Apparat bearbeiten
</div>

TBD

app/views/admin/sem_apps/index.html.erb
<h3 class="section">Seminarapparate verwalten</h3>

<div class="grid_8 alpha">
  <%= render 'listing' %>
</div>

<div class="grid_4 omega">
  <div class="pui-panel">
    <%= form_tag filter_admin_sem_apps_path do %>
      <p>
        <%= check_box_tag "filter[unapproved]", '1', @filter.unapproved %>
        <label>Nur <strong>neue</strong> Seminarapparate</label>
      </p>
      <p>
        <%= check_box_tag "filter[book_jobs]", '1', @filter.book_jobs %>
        <label>Nur Buchaufträge</label>
      </p>
      <p>
        <label>Semester</label><br/>
        <%= collection_select(:filter, :semester_id, Semester.order('position ASC'), :id, :title, {:include_blank => "Alle"}, {:style => 'width: 195px'}) %>
      </p>
      <p>
        <label>Standort</label><br/>
        <%= collection_select(:filter, :location_id, Location.all, :id, :title, {:include_blank => "Alle"}, {:style => 'width: 195px'}) %>
      </p>
      <p>
        <label>Titel</label><br/>
        <%= text_field_tag "filter[title]", @filter.title, {:style => 'width: 190px'} %>
      </p>
      <p>
        <label>Dozent</label><br/>
        <%= text_field_tag "filter[tutors]", @filter.tutors, {:style => 'width: 190px'}  %>
      </p>
      <p>
        <label>Besitzer (Name oder PA Nr.)</label><br/>
        <%= text_field_tag "filter[creator]", @filter.creator, {:style => 'width: 190px'}  %>
      </p>
      <p>
        <label>Buch Ausweis (PE Nr.)</label><br/>
        <%= text_field_tag "filter[ils_account]", @filter.ils_account, {:style => 'width: 190px'}  %>
      </p>
      <p>
        <label>Seminarapparat Nr.</label><br/>
        <%= text_field_tag "filter[slot_number]", @filter.slot_number, {:style => 'width: 190px'}  %>
      </p>
      <div class="align-center">
        <%= submit_tag 'Filtern' %>
        <% if @filtered %>
          <%= link_to 'Zurücksetzen', filter_admin_sem_apps_path, :method => :post %>
        <% end %>
      </div>
    <% end %>
  </div>

  <p><i>Sortiert nach Datum der Beantragung</i></p>
</div>